reviews:
  auto_title_instructions: "Generate a concise, descriptive PR title under 50 characters that summarizes the main purpose of these changes"
  auto-title-placeholder: "@coderabbitai generate title"
